// Code generated by hertz generator.

package message

import (
	"context"

	message "BiteDans.com/tiktok-backend/biz/model/douyin/extra/message"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// MessageSend .
// @router /douyin/message/action/ [POST]
func MessageSend(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.DouyinRelationActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(message.DouyinRelationActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// MessageHistory .
// @router /douyin/message/chat/ [GET]
func MessageHistory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.DouyinMessageChatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(message.DouyinMessageChatResponse)

	c.JSON(consts.StatusOK, resp)
}
