// Code generated by hertz generator.

package main

import (
	"os"

	"BiteDans.com/tiktok-backend/biz/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	// f, err := os.OpenFile("./output.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	// if err != nil {
	// 	panic(err)
	// }
	// defer f.Close()

	hlog.SetOutput(os.Stdout)
	hlog.SetLevel(hlog.LevelInfo)

	h := server.Default()

	dal.Init()

	register(h)
	h.Spin()
}
