// Code generated by hertz generator.

package main

import (
	"os"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	h := server.Default()
	f, err := os.OpenFile("./output.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
    if err != nil {
		panic(err)
    }
    defer f.Close()
    hlog.SetOutput(f)
	hlog.SetLevel(hlog.LevelInfo)
	register(h)
	h.Spin()
}
