// Code generated by hertz generator.

package follow

import (
	"BiteDans.com/tiktok-backend/biz/dal/model"
	"BiteDans.com/tiktok-backend/pkg/utils"
	"context"

	follow "BiteDans.com/tiktok-backend/biz/model/douyin/extra/follow"
	_ "BiteDans.com/tiktok-backend/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FollowAction .
// @router /douyin/relation/action [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.DouyinRelationActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(follow.DouyinRelationActionResponse)
	curUserReq := req.Token
	curUserId, err1 := utils.GetIdFromToken(curUserReq)
	if err1 != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	curUser := new(model.User)
	if err := model.FindUserById(curUser, curUserId); err != nil {
		return
	}
	toUserId := req.ToUserId
	toUser := new(model.User)
	if err := model.FindUserById(toUser, uint(toUserId)); err != nil {
		return
	}
	actionType := req.ActionType
	if err := model.UserFollowAction(curUser, toUser, uint(actionType)); err != nil {
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// FollowList .
// @router /douyin/relation/follow/list/ [GET]
func FollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.DouyinRelationFollowListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(follow.DouyinRelationFollowListResponse)

	c.JSON(consts.StatusOK, resp)
}

// FollowerList .
// @router /douyin/relation/follower/list/ [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.DouyinRelationFollowerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(follow.DouyinRelationFollowerListResponse)

	c.JSON(consts.StatusOK, resp)
}
