// Code generated by hertz generator.

package user

import (
	"context"

	"BiteDans.com/tiktok-backend/biz/dal/model"
	"BiteDans.com/tiktok-backend/biz/model/douyin/core/user"
	"BiteDans.com/tiktok-backend/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UserInfo .
// @router /douyin/user [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.DouyinUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.DouyinUserResponse)

	//TODO: get current user id and determine if the
	//target user is followed by current user
	if _, err = utils.GetIdFromToken(req.Token); err != nil {
		resp.StatusCode = -1
		resp.StatusMsg = "Invalid token"
		resp.User = nil

		c.JSON(consts.StatusUnauthorized, resp)
		return
	}

	_user := new(model.User)

	if err = model.FindUserById(_user, uint(req.UserId)); err != nil {
		resp.StatusCode = -1
		resp.StatusMsg = "User id does not exist"
		resp.User = nil
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	resp.StatusCode = 0
	resp.StatusMsg = "User info retrieved successfully"
	resp.User = &user.User{
		ID:            int64(_user.ID),
		Name:          _user.Username,
		FollowCount:   123,
		FollowerCount: 456,
		IsFollow:      true,
	}

	c.JSON(consts.StatusOK, resp)
}

// UserLogin .
// @router /douyin/user/login/ [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.DouyinUserLoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.DouyinUserLoginResponse)
	user := new(model.User)

	user.Username = req.Username
	user.Password = req.Password

	var inputpassword = user.Password

	if err = model.FindUserByUsername(user, req.Username); err != nil {
		resp.StatusCode = -1
		resp.StatusMsg = "Failed to log in (Username not found)"
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	if inputpassword != user.Password {
		resp.StatusCode = -1
		resp.StatusMsg = "Failed to log in (Incorrect password)"
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	var token string

	if token, err = utils.GenerateJWT(user.ID); err != nil {
		resp.StatusCode = -1
		resp.StatusMsg = "Failed to log in (Token generation failed)"
		c.JSON(consts.StatusInternalServerError, resp)

		hlog.Error("Failed to generate token")
		return
	}

	resp.StatusCode = 0
	resp.StatusMsg = "User logged in successfully"
	resp.UserId = int64(user.ID)
	resp.Token = token

	c.JSON(consts.StatusOK, resp)
}

// UserRegister .
// @router /douyin/user/register/ [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.DouyinUserRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.DouyinUserRegisterResponse)
	user := new(model.User)

	if err = model.FindUserByUsername(user, req.Username); err == nil {
		resp.StatusCode = -1
		resp.StatusMsg = "Username has been used"
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	user.Username = req.Username
	user.Password = req.Password

	if err = model.CreateUser(user); err != nil {
		resp.StatusCode = -1
		resp.StatusMsg = "Failed to register user"
		c.JSON(consts.StatusInternalServerError, resp)

		hlog.Error("Failed to create user into database")
		return
	}

	var token string

	if token, err = utils.GenerateJWT(user.ID); err != nil {
		resp.StatusCode = -1
		resp.StatusMsg = "Failed to log in (Token generation failed)"
		c.JSON(consts.StatusInternalServerError, resp)

		hlog.Error("Failed to generate token")
		return
	}

	resp.StatusCode = 0
	resp.StatusMsg = "User registered successfully"
	resp.UserId = int64(user.ID)
	resp.Token = token

	c.JSON(consts.StatusOK, resp)
}
